"""M3 UART command and response codes."""

CMD_CHARGER_STATUS = 0x40
RESP_CHARGER_STATUS = 0x80

CMD_BATTERY_STATUS = 0x44
RESP_BATTERY_STATUS = 0x84

CMD_ALARM_STATUS = 0x46
RESP_ALARM_STATUS = 0x86

CMD_FIRMWARE_VERSION = 0x70
RESP_FIRMWARE_VERSION = 0xF0

BATTERY_SLOT_A = 0x00
BATTERY_SLOT_B = 0x01

_RTC_SIZE = 8  # uint16 year + uint8 month/day/weekday/hour/minute/second
